### ISSUE TITLE
CSS file doesn't work well

### ISSUE THREAD

**Issue by ryzzn** [kookma/TW-Timelines#1]
Hi, @kookma . I really love your timeline plugin but it doesn't work well when some tiddlers have `<li></li>` itself. It is fixed when I change the css selector from `.kk-tl-kerman ul li` to `.kk-tl-kerman >ul >li` and some others. Maybe it can be fixed in your repo, Thanks.

**Comment by kookma** [comment]
@ryzzn Thank you!

It seems this is a bug! I will check the code and will push a patch.

**Comment by xgadscu** [comment]
Also, I noticed that the date parameter is not working correctly. If I change the date parameter from modified to date, the order of the tiddlers does not change. But that is the purpose of the timeline.

`
<<timeline-vertical filter:"[tag[exmp]]" date:date class:success>>`

![2022-11-09 16_47_46-Timelines plugin — wrong order](https://user-images.githubusercontent.com/42093828/200876430-9786fbee-8131-4698-a30b-c5c0d8a67f2f.png)

**Comment by kookma** [comment]
Has the date field correct format? Use standard TW date format and check again!

**Comment by xgadscu** [comment]
In fact I used the format yyyymmdd. When I saw the date field in your plugin's Demo tiddlers, I thought the default date format would be smart enough to pad yyyymmdd with the missing digits.
Now I tried it with the correct date format and it still doesn't work. When I reset back to the default "modified", the tiddlers do not appear in the order I changed them.

Please have a look at the attached tiddlers based on your Demo. You can also try it in your Demo-Wiki.
[timeline-date.zip](https://github.com/kookma/TW-Timelines/files/9980836/timeline-date.zip)

In any case I would recommend that you change the date field in the Demo tiddlers to TW standard format to avoid further irritation.

**Comment by kookma** [comment]
Ah you did not sort the list!

Note that the timeline does not sort the input itself. For example

```
<<timeline-vertical filter:"[tag[exmp]nsort[date]]" date:date class:success>>
```

Sorts the event based on NUMBER is given in date field.

You can also use sort run prefix to use date as data type.

So this is not a bug!

By the way I will update plugin to TW 5.2.3 and will add examples

**Comment by kookma** [comment]
I think the docs are not clear and makes confusion. I will update docs also.

**Comment by xgadscu** [comment]
Hi @kookma, thank you very much. I had already wondered why you can't set whether to sort ascending or descending. Now it works as expected.

By the way: If I use the date field in the form yyyymmdd, it also works.

**Comment by kookma** [comment]
Great to hear that!
