### ISSUE TITLE
Date field value showing incorrectly on timelines

### ISSUE THREAD

**Issue by f10oreo** [kookma/TW-Timelines#3]
I'm not really sure how to troubleshoot this, but my dates are shifting one day ahead.

As an example, I have a tiddler with the field "date" and the value "08180508" which should show up as 0818 May 8th, but on the timeline it'll show as May 7th. I haven't modified the code at all, just dropped the plugin into my wiki.

![Screen Shot 2021-11-04 at 2 12 51 AM](https://user-images.githubusercontent.com/26267151/140288046-9fdaedca-f9ce-43c7-b673-1933ae7e658c.png)
![Screen Shot 2021-11-04 at 2 12 32 AM](https://user-images.githubusercontent.com/26267151/140288052-914f441e-b93b-4876-812d-d783038e00ae.png)

**Comment by kookma** [comment]
The date is like this `YYYY0MM0DD` so 2018-10-15 is `20181015`
Check and let me know!

**Comment by f10oreo** [comment]
Still having the same problem, unfortunately. If I put in `20181015` it gives me the date as 2018-10-14. 

I went to your github demo page and it seems to be having the same issue (at least for me). Your Second Tiddler is dated `20130928` but the timeline says Sep 27th instead of 28.

![Screen Shot 2021-11-04 at 11 25 21 AM](https://user-images.githubusercontent.com/26267151/140398403-15ad36f7-7735-4a2a-b6e9-4f9f84269e0b.png)
![Screen Shot 2021-11-04 at 11 25 33 AM](https://user-images.githubusercontent.com/26267151/140398401-694412e0-6df9-48f8-a65b-455e0dbd2784.png)

**Comment by kookma** [comment]
I checked the dates both on https://kookma.github.io/TW-Timelines/ and on https://tiddlywiki.com/prerelease/ and they work!
You may have a look at https://talk.tiddlywiki.org/ and raise your question!
May be there is an issue somewhere else!

**Comment by f10oreo** [comment]
Thanks for the link, I'll ask over there and let you know if they can help me find the issue!

**Comment by f10oreo** [comment]
Posted about it [here](https://talk.tiddlywiki.org/t/kookmas-timelines-macro-date-in-timeline-is-one-day-ahead-of-date-in-tiddler/1436/2) and it has to do with timezone offset! A suggested workaround is adding time to the date value (specifically noon) in order to keep the days the same and that's worked for me

**Comment by kookma** [comment]
This answered by Eric Shulman at https://talk.tiddlywiki.org/t/kookmas-timelines-macro-date-in-timeline-is-one-day-ahead-of-date-in-tiddler/1436
